import { useState, useRef } from "react";

const cx = (...a) => a.filter(Boolean).join(" ");

export default function AIFeedbackPanel({ text }) {
  const [expanded,     setExpanded]     = useState(true);
  const [audioLoading, setAudioLoading] = useState(false);
  const [isPlaying,    setIsPlaying]    = useState(false);
  const audioRef = useRef(null);

  if (!text) return null;

  const handleListen = async () => {
    if (isPlaying && audioRef.current) {
      audioRef.current.pause();
      audioRef.current = null;
      setIsPlaying(false);
      return;
    }

    setAudioLoading(true);
    try {
      const form = new FormData();
      form.append("text", text);
      form.append("language", "en-IN");

      const res = await fetch("http://127.0.0.1:8000/voice/tts", {
        method: "POST",
        body: form,
      });
      if (!res.ok) throw new Error(`TTS failed (${res.status})`);

      const blob  = await res.blob();
      const url   = URL.createObjectURL(blob);
      const audio = new Audio(url);
      audioRef.current = audio;

      audio.onended = () => { setIsPlaying(false); URL.revokeObjectURL(url); audioRef.current = null; };
      audio.onerror = () => { setIsPlaying(false); URL.revokeObjectURL(url); audioRef.current = null; };

      await audio.play();
      setIsPlaying(true);
    } catch (err) {
      console.error("TTS error:", err);
    } finally {
      setAudioLoading(false);
    }
  };

  return (
    <div className="rounded-2xl border border-indigo-100 bg-gradient-to-br from-indigo-50/70 to-purple-50/40 p-5 h-full">
      {/* Header */}
      <div className="flex items-center gap-2 mb-4">
        <div>
          <div className="text-sm font-bold text-indigo-800">AI Study Plan</div>
          <div className="text-[11px] text-indigo-400 mt-0.5">Generated by Sarvam-M</div>
        </div>

        {/* Listen button */}
        <button
          onClick={handleListen}
          disabled={audioLoading}
          className={cx(
            "ml-auto flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold transition-all duration-200 shadow-sm",
            audioLoading
              ? "bg-slate-100 text-slate-400 cursor-not-allowed"
              : isPlaying
              ? "bg-red-500 hover:bg-red-600 text-white shadow-red-200"
              : "bg-indigo-600 hover:bg-indigo-700 text-white shadow-indigo-200"
          )}
        >
          {audioLoading ? (
            <>
              <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z"/>
              </svg>
              Generating…
            </>
          ) : isPlaying ? (
            <>
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <rect x="6" y="6" width="12" height="12" rx="2"/>
              </svg>
              Stop
            </>
          ) : (
            <>
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <path d="M3 9v6h4l5 5V4L7 9H3zm13.5 3c0-1.77-1.02-3.29-2.5-4.03v8.05c1.48-.73 2.5-2.25 2.5-4.02z"/>
              </svg>
              Listen to Plan
            </>
          )}
        </button>
      </div>

      {/* Divider */}
      <div className="border-t border-indigo-100 mb-4" />

      {/* Full text — scrollable if tall */}
      <div
        className="text-sm text-slate-700 leading-relaxed whitespace-pre-line overflow-y-auto"
        style={{ maxHeight: "calc(100vh - 260px)" }}
      >
        {text}
      </div>
    </div>
  );
}